INSERT INTO TURBINAS (ANGULO, ALTURA, VELOCIDAD_MAX, ENCENDIDO, CARGA) VALUES ('30','107','50',TRUE,'18');
INSERT INTO TURBINAS (ANGULO, ALTURA, VELOCIDAD_MAX, ENCENDIDO, CARGA) VALUES ('30','104','52',TRUE,'27');
INSERT INTO TURBINAS (ANGULO, ALTURA, VELOCIDAD_MAX, ENCENDIDO, CARGA) VALUES ('35','102','53',TRUE,'12');
INSERT INTO TURBINAS (ANGULO, ALTURA, VELOCIDAD_MAX, ENCENDIDO, CARGA) VALUES ('40','107','52',FALSE,'0');
INSERT INTO TURBINAS (ANGULO, ALTURA, VELOCIDAD_MAX, ENCENDIDO, CARGA) VALUES ('30','105','52',TRUE,'10');
INSERT INTO TURBINAS (ANGULO, ALTURA, VELOCIDAD_MAX, ENCENDIDO, CARGA) VALUES ('40','110','50',FALSE,'0');

INSERT INTO USUARIO (CORREO, PASSW) VALUES ('sexoculo@gmail.com', '{noop}abc123');
INSERT INTO USUARIO (CORREO, PASSW) VALUES ('farloperez@gmail.com', '{noop}abc123');
INSERT INTO USUARIO (CORREO, PASSW) VALUES ('pito@gmail.com', '{noop}abc123');

INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (23, 'Soleado', 3, 45);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (10, 'Lluvia fuerte', 69, 69);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (15, 'Apocalipsis nuclear', 25, 15);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (35, 'Nublado', 30, 29);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (34, 'Soleado', 0, 23);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (15, 'Lluvia fuerte', 69, 56);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (33, 'Soleado',3 , 12);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (20, 'Nublado', 6, 34);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (25, 'Soleado', 0, 45);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (4, 'Lluvia fuerte', 67, 80);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (5, 'Nublado', 5, 15);
INSERT INTO CLIMA (TEMPERATURA, DESCRIPCION, PRECIPITACION, VELOCIDAD_VIENTO) VALUES (9, 'Nublado', 0, 29);

INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (43, 220, 14, 'Bajo rendimiento', 1);
INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (48, 220, 11, 'Bajo rendimiento', 1);
INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (0, 110, 2, 'Reposo', 2);
INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (0, 110, 3, 'Reposo', 3);
INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (2578, 220, 77, 'Alto rendimiento',3);
INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (2212, 220, 81, 'Alto rendimiento',4);
INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (0, 220, 2, 'Apagado',5);
INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (0, 220, 3, 'Apagado',5);
INSERT INTO GENERADOR (RPM, VOLTAJE, PRESION, ESTADO, TURBINA_ID) VALUES (57, 220, 12, 'Bajo rendimiento',5);

INSERT INTO CONTACTO (NOMBRE, APELLIDOS, CORREO, DIRECCION, PAIS, ESTADO, ZIP, TARIFA, DESEA_PROMO, DESEA_COM) VALUES ('Bruno', 'Sanhuan', 'brunardo@gmail.com','Calle Costa Brava 20 2 Der', 'Guinea Ecuatorial', 'Ciudad Real', 28034, 'Plan de ahorro dos tramos', TRUE, FALSE);
INSERT INTO CONTACTO (NOMBRE, APELLIDOS, CORREO, DIRECCION, PAIS, ESTADO, ZIP, TARIFA, DESEA_PROMO, DESEA_COM) VALUES ('Pedro', 'de la Rosa', 'vueltarapida@hotmail.com','Calle Ibai Llanos 15 5 A', 'Andorra', NULL, 18929, 'Plan de ahorro tres tramos', TRUE, TRUE);