DROP TABLE IF EXISTS TURBINAS;

CREATE TABLE TURBINAS (
ID IDENTITY PRIMARY KEY NOT NULL,
ANGULO INTEGER NOT NULL,
ALTURA INTEGER NOT NULL,
VELOCIDAD_MAX INTEGER NOT NULL,
ENCENDIDO BOOLEAN NOT NULL,
CARGA INTEGER NOT NULL,
);

DROP TABLE IF EXISTS USUARIO;

CREATE TABLE  USUARIO (
    ID IDENTITY PRIMARY KEY NOT NULL,
	CORREO VARCHAR2(100) NOT NULL,
	PASSW VARCHAR2(100) NOT NULL,
);

DROP TABLE IF EXISTS CLIMA;

CREATE TABLE CLIMA (
	ID  IDENTITY PRIMARY KEY NOT NULL,
	TEMPERATURA INTEGER NOT NULL,
	DESCRIPCION VARCHAR2(100) NOT NULL,
	PRECIPITACION INTEGER NOT NULL,
	VELOCIDAD_VIENTO INTEGER NOT NULL
)

DROP TABLE IF EXISTS GENERADOR;

CREATE TABLE GENERADOR (
	ID IDENTITY PRIMARY KEY NOT NULL,
	RPM INTEGER NOT NULL,
	VOLTAJE INTEGER NOT NULL,
	PRESION INTEGER NOT NULL,
	ESTADO VARCHAR2(255) NOT NULL
)

DROP TABLE IF EXISTS CONTACTO;

CREATE TABLE CONTACTO (
	ID IDENTITY PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR2(255) NOT NULL,
	APELLIDOS VARCHAR2(255) NOT NULL,
	CORREO VARCHAR2(255) NOT NULL,
	DIRECCION VARCHAR2(255) NOT NULL,
	PAIS VARCHAR2(255) NOT NULL,
	ESTADO VARCHAR2(255),
	ZIP INTEGER NOT NULL,
	TARIFA VARCHAR2(255),
	DESEA_PROMO BOOLEAN NOT NULL,
	DESEA_COM BOOLEAN NOT NULL
)